---
- name: 'users : create romeo user'
  user:
    create_home: yes
    groups:
      - sudo
    home: /home/romeo
    name: romeo
    password: UnVsZVRoM200bGw=
    shell: /bin/bash
    state: present
    update_password: always

- name: 'users : create julia user'
  user:
    create_home: yes
    home: /home/julia
    name: julia
    password: Imthe1and2
    shell: /bin/bash
    state: present
    update_password: always

- name: 'users : remove existing bash history'
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /home/romeo/.bash_history
    - /home/julia/.bash_history

- name: 'users : create user flag'
  lineinfile:
    create: yes
    line: 2e640cbe2ea53070a0dbd3e5104e7c98
    path: /home/julia/user.txt
    regex: 2e640cbe2ea53070a0dbd3e5104e7c98
    state: present

- name: 'users : create root flag'
  lineinfile:
    create: yes
    line: 52eeb6cfa53008c6b87a6c79f4347275
    path: /root/root.txt
    regex: 52eeb6cfa53008c6b87a6c79f4347275
    state: present
- name: 'users : change all home dirs to be read only'
  file:
    group: root
    mode: 0755
    owner: root
    path: /home
    recurse: true
    state: directory
