---
- name: 'users : create romeo'
  user:
    create_home: yes
    groups:
      - sudo
    home: /home/romeo
    name: romeo
    password: $6$QXiSjpwcO/MBf931$HqHzV3MQFeJ.sQkkugh12ZcKlkxl9lNzl5esUWgkaPJN6SGNBY79i6Vc1FFWWwkMQ4wAisl1qqWdqWS0JZbI70
    shell: /bin/bash
    state: present
    update_password: always

- name: 'users : create julia'
  user:
    create_home: yes
    home: /home/julia
    name: julia
    password: $6$jA5hT3due05rvFWj$EHdfjk98ehbZBkJmw2CJu.xXOLwAEkMjXH5atFtIdYvQdV820d2rE98bi415fc7e8sVLoaLMIAh0S6FUYKvaw.
    shell: /bin/bash
    state: present
    update_password: always

- name: 'user flag'
  lineinfile:
    create: yes
    line: 2e640cbe2ea53070a0dbd3e5104e7c98
    path: /home/julia/flag1.txt
    regex: 2e640cbe2ea53070a0dbd3e5104e7c98
    state: present

- name: 'Sor beillesztés flag 1'
  ansible.builtin.lineinfile:
    path: /home/julia/flag1.txt
    line: romeo for root UnVsZVRoZW1BbGw=
    create: yes

- name: 'root flag'
  lineinfile:
    create: yes
    line: 52eeb6cfa53008c6b87a6c79f4347275
    path: /root/flag2.txt
    regex: 52eeb6cfa53008c6b87a6c79f4347275
    state: present
