---
- name: 'users : create tatham user'
  user:
    create_home: yes
    groups:
      - sudo
    home: /home/tatham
    name: tatham
    password: UnVsZVRoM200bGw=
    shell: /bin/bash
    state: present
    update_password: always

- name: 'users : create julian user'
  user:
    create_home: yes
    home: /home/julian
    name: julian
    password: SW10aGUxYW5kMg==
    shell: /bin/bash
    state: present
    update_password: always

- name: 'users : remove existing bash history'
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /home/tatham/.bash_history
    - /home/julian/.bash_history

- name: 'users : create user flag'
  lineinfile:
    create: yes
    line: 2e640cbe2ea53070a0dbd3e5104e7c98
    path: /home/julian/user.txt
    regex: 2e640cbe2ea53070a0dbd3e5104e7c98
    state: present

- name: 'users : create root flag'
  lineinfile:
    create: yes
    line: 52eeb6cfa53008c6b87a6c79f4347275
    path: /root/root.txt
    regex: 52eeb6cfa53008c6b87a6c79f4347275
    state: present
- name: 'users : change all home dirs to be read only'
  file:
    group: root
    mode: 0755
    owner: root
    path: /home
    recurse: true
    state: directory
