---
- name: 'mysql : install python 2.7'
  apt:
    name: python
    state: present
    update_cache: yes

- name: 'mysql : honeypot másolása'
  copy:
    dest: /root/mysql.py
    src: ../files/honeypot.py

- name: 'mysql : honeypot service'
  copy:
    dest: /etc/systemd/system/mysql.service
    src: ../files/mysql.service

- name: 'mysql : service engedélyezése'
  systemd:
    daemon_reload: yes
    enabled: yes
    force: yes
    name: mysql
    state: started
