- name: Mysql telepites fuggosegekkel
  become: yes
  tasks:
    -  name: telepites
       package:
          name: "{{item}}"
          state: present
          update_cache: yes
       loop:
         - mysql-server
         - mysql-client
         - python3-mysqldb
         - libmysqlclient-dev
       become: yes
      
    - name: mysql service engedelyezese es indítasa
      service:
         name: mysql
         state: started
         enabled: yes

    - name: mysql user keszites
      mysql_user:
         name: romeo
         password: julia
         priv: '*.*:ALL'
         host: '%'
         state: present
     
    - name: db keszítes
      mysql_db:
         name: HOME
         state: present

    - name: remote login engedelyezese
      lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
         backup: yes


    - name: Restart mysql
      service: 
        daemon_reload: yes
        enabled: yes
        name: mysql
        state: restarted
