- name: directory létrehozása
  file:
    path: $HOME/docker-web
    state: directory
    mode: '0755'

- name: dockerfile másolása
  copy:
      src: "~/ansible-TB/1/roles/web/docker/Dockerfile"
      dest: $HOME/docker-web/Dockerfile
      mode: '0744'
      force: yes

- name: entrypoint script másolása
  copy:
      src: "~/ansible-TB/1/roles/web/resources/entrypoint.sh"
      dest: $HOME/docker-web/entrypoint.sh
      mode: '0744'
      force: yes

- name: ports.conf másolása
  copy:
      src: "~/ansible-TB/1/roles/web/resources/ports.conf"
      dest: $HOME/docker-web/ports.conf
      mode: '0700'
      force: yes

- name: default site conf másolása
  copy:
      src: "~/ansible-TB/1/roles/web/resources/000-default.conf"
      dest: $HOME/docker-web/000-default.conf
      mode: '0700'
      force: yes

- name: php.ini másolása
  copy:
      src: "~/ansible-TB/1/roles/web/resources/php.ini"
      dest: $HOME/docker-web/php.ini
      mode: '0700'
      force: yes

- name: Web tartalom  másolása
  copy:
      src: "~/ansible-TB/1/roles/web/resources/web_content/"
      dest: $HOME/docker-web/web_content/
      mode: '1700'
      force: yes

- name: Build image
  docker_image:
    name: web-image
    build:
      path: $HOME/docker-web/
      pull: yes
    source: build
    state: present
    force_source: yes
    repository: web-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    container_default_behavior: compatibility
    name: web
    image: web-image
    state: started
    restart: yes
    expose: 8006
    detach: yes
    published_ports: '8006:8006'
