- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-linux
    state: directory
    mode: '0755'

- name: Copy dockefile
  copy:
      src: "~/ansible-TB/5/roles/linux/docker/Dockerfile"
      dest: /tmp/docker-linux/Dockerfile
      mode: '0744'
      force: yes

- name: Copy entrypoint script
  copy:
      src: "~/ansible-TB/5/roles/linux/resources/entrypoint.sh"
      dest: /tmp/docker-linux/entrypoint.sh
      mode: '0744'
      force: yes

- name: Copy vsftpd config
  copy:
      src: "~/ansible-TB/5/roles/linux/resources/vsftpd.conf"
      dest: /tmp/docker-linux/vsftpd.conf
      mode: '0744'
      force: yes

- name: Build image
  docker_image:
    name: linux-image
    build:
      path: /tmp/docker-linux/
    source: build
    state: present
    force_source: yes
    repository: linux-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: linux
    image: linux-image
    state: started
    restart: yes
    expose: 21
    detach: yes
    published_ports: "10000-10100:10000-10100, 6013:6013, 20:20"
