---
- name: 'apache : install packages'
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - php8.0
      - php8.0-xml
      - php8.0-mbstring
      - php8.0-curl
      - php8.0-mysql
    state: present
    update_cache: yes

- name: 'apache : enable mysqli.allow_local_infile'
  lineinfile:
    line: mysqli.allow_local_infile = On
    path: /etc/php/8.0/apache2/php.ini
    regex: mysqli.allow_local_infile = On
    state: present

- name: 'apache : rejtett mappa készítés'
  file:
    path: /var/www/html/ide rejtek valamit
    state: directory
