---
- name: 'romeo user letrehozas'
  user:
    create_home: yes
    groups:
      - sudo
    home: /home/romeo
    name: romeo
    password: julia
    shell: /bin/bash
    state: present
    update_password: always

- name: 'julia user letrehozas'
  user:
    create_home: yes
    home: /home/julia
    name: julia
    password: romeo
    shell: /bin/bash
    state: present
    update_password: always

- name: 'ufw engedelyezes'
  apt:
    name: ufw
    state: present

- name: 'bejovo forgalom tiltasa'
  ufw:
    state: enabled
    direction: incoming
    policy: deny

- name: 'port 22, 80, 3306'
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - 22
    - 80
    - 3306
